/**
 * Seed script: migrasikan 9 kursus + 45 AI reviews + 9 ASKOM reviews
 * dari konstanta statis marketplace.tsx ke tabel DB.
 *
 * Run: cd lib/db && npx tsx src/seed-marketplace.ts
 */

import { db } from "./index";
import { marketplaceCourses, marketplaceAiReviews, marketplaceAskomReviews } from "./schema";

// ─── Course data ───────────────────────────────────────────────────────────────

const COURSES = [
  {
    id: "k3-dasar-pupr",
    title: "K3 Konstruksi Dasar — Standar PUPR & BNSP",
    provider: "Kemnaker Diklatkerja",
    providerLogo: "🏛️",
    thumbnail: "from-orange-500 to-red-500",
    type: "diklatkerja",
    price: "gratis",
    priceIdr: null,
    priceOriginalIdr: null,
    rating: 4.8,
    ratingCount: 1240,
    durationMinutes: 480,
    videoCount: 28,
    quizCount: 8,
    hasCertificate: true,
    jabker: ["ahli_k3_konstruksi", "pengawas_k3_konstruksi"],
    skkTags: [
      { code: "F.45.2.0.0.0.0.0.01", name: "Menerapkan SMK3 pada Proyek Konstruksi" },
      { code: "F.45.2.0.0.0.0.0.02", name: "Melaksanakan Inspeksi K3 di Lapangan" },
    ],
    description: "Rekaman diklatkerja resmi Kemnaker membahas penerapan Sistem Manajemen K3 (SMK3) pada proyek konstruksi, prosedur inspeksi lapangan, penanganan insiden, dan dokumentasi K3 sesuai standar PUPR.",
    highlights: [
      "Modul SMK3 berbasis ISO 45001 & PP 50/2012",
      "Studi kasus insiden konstruksi nyata",
      "Formulir inspeksi K3 siap pakai",
      "Relevan untuk ujian SKK Jenjang 6–8",
    ],
    curriculum: [
      { title: "Pengantar SMK3 di Sektor Konstruksi", duration: "45 mnt", type: "video" },
      { title: "Regulasi K3 Konstruksi (PP, Permen PUPR)", duration: "60 mnt", type: "video" },
      { title: "Quiz: Regulasi & Dasar SMK3", duration: "15 mnt", type: "quiz" },
      { title: "Identifikasi Bahaya & Penilaian Risiko", duration: "90 mnt", type: "video" },
      { title: "Prosedur Inspeksi K3 Harian", duration: "75 mnt", type: "video" },
      { title: "Quiz: Inspeksi & Penilaian Risiko", duration: "15 mnt", type: "quiz" },
      { title: "Penanganan Insiden & Pelaporan", duration: "60 mnt", type: "video" },
      { title: "Studi Kasus: Insiden Jatuh dari Ketinggian", duration: "45 mnt", type: "video" },
    ],
    url: "https://www.diklatkerja.kemnaker.go.id",
    isBestSeller: true,
    isFeatured: true,
    isNew: false,
    sortOrder: 1,
  },
  {
    id: "qs-bop-perhitungan",
    title: "Perhitungan BOP & RAB Konstruksi Gedung",
    provider: "Skill Academy Pro",
    providerLogo: "🎓",
    thumbnail: "from-blue-500 to-cyan-500",
    type: "video",
    price: "berbayar",
    priceIdr: 199000,
    priceOriginalIdr: 399000,
    rating: 4.9,
    ratingCount: 876,
    durationMinutes: 510,
    videoCount: 32,
    quizCount: 12,
    hasCertificate: true,
    jabker: ["quantity_surveyor"],
    skkTags: [
      { code: "M.711000.003.01", name: "Menghitung Volume Pekerjaan Konstruksi" },
      { code: "M.711000.005.01", name: "Menyusun Rencana Anggaran Biaya (RAB)" },
      { code: "M.711000.007.01", name: "Menganalisis Harga Satuan Pekerjaan" },
    ],
    description: "Kelas komprehensif menghitung Bill of Quantity, RAB, dan analisa harga satuan untuk proyek gedung bertingkat. Dilengkapi template Excel dan studi kasus proyek nyata.",
    highlights: [
      "Template Excel BOQ & RAB langsung pakai",
      "SNI harga satuan terbaru 2024",
      "Studi kasus gedung 5 lantai",
      "Sertifikat Skill Academy Pro (dapat digunakan sebagai bukti PKB)",
    ],
    curriculum: [
      { title: "Konsep Dasar Estimasi Biaya Konstruksi", duration: "35 mnt", type: "video" },
      { title: "Membaca Gambar Kerja untuk QS", duration: "50 mnt", type: "video" },
      { title: "Menghitung Volume Pekerjaan Tanah", duration: "60 mnt", type: "video" },
      { title: "Quiz: Volume & Takup", duration: "15 mnt", type: "quiz" },
      { title: "Analisa Harga Satuan SNI", duration: "75 mnt", type: "video" },
      { title: "Menyusun RAB Lengkap", duration: "90 mnt", type: "video" },
      { title: "Quiz: RAB & HSP", duration: "20 mnt", type: "quiz" },
      { title: "Manajemen Perubahan (Change Order)", duration: "45 mnt", type: "video" },
    ],
    url: "https://skillacademy.com",
    isBestSeller: true,
    isFeatured: false,
    isNew: false,
    sortOrder: 2,
  },
  {
    id: "pengawas-lapangan-mutu",
    title: "Pengendalian Mutu Pekerjaan Struktur Beton",
    provider: "LPJK Webinar Series",
    providerLogo: "🏗️",
    thumbnail: "from-emerald-500 to-teal-500",
    type: "webinar",
    price: "gratis",
    priceIdr: null,
    priceOriginalIdr: null,
    rating: 4.7,
    ratingCount: 2341,
    durationMinutes: 240,
    videoCount: 12,
    quizCount: 4,
    hasCertificate: true,
    jabker: ["pengawas_lapangan", "ahli_struktur"],
    skkTags: [
      { code: "F.45.2.0.1.1.0.76.II.01", name: "Melakukan Pengendalian Mutu Beton" },
      { code: "F.45.2.0.1.1.0.76.II.02", name: "Memeriksa Pekerjaan Bekisting" },
    ],
    description: "Webinar resmi LPJK membahas prosedur pengendalian mutu beton di lapangan — mulai dari mix design, slump test, pengujian silinder beton, hingga acceptance criteria sesuai SNI.",
    highlights: [
      "Prosedur slump test & uji kuat tekan beton",
      "Formulir pengendalian mutu lapangan",
      "Syarat penerimaan beton SNI 2847-2019",
      "Rekaman webinar LPJK (dapat sebagai bukti CPD)",
    ],
    curriculum: [
      { title: "Mix Design Beton & Spesifikasi Teknis", duration: "40 mnt", type: "video" },
      { title: "Pengambilan Sampel & Slump Test", duration: "35 mnt", type: "video" },
      { title: "Uji Kuat Tekan Silinder Beton", duration: "45 mnt", type: "video" },
      { title: "Quiz: Pengendalian Mutu Beton", duration: "15 mnt", type: "quiz" },
      { title: "Cacat Pengerjaan & Tindakan Korektif", duration: "50 mnt", type: "video" },
    ],
    url: "https://lpjk.pu.go.id",
    isBestSeller: false,
    isFeatured: false,
    isNew: true,
    sortOrder: 3,
  },
  {
    id: "mep-koordinasi-bim",
    title: "Koordinasi MEP dengan BIM — Revit MEP Dasar",
    provider: "Autodesk Learning",
    providerLogo: "💻",
    thumbnail: "from-violet-500 to-purple-500",
    type: "video",
    price: "berbayar",
    priceIdr: 350000,
    priceOriginalIdr: 700000,
    rating: 4.8,
    ratingCount: 543,
    durationMinutes: 600,
    videoCount: 38,
    quizCount: 10,
    hasCertificate: true,
    jabker: ["ahli_mekanikal_elektrikal", "ahli_plumbing"],
    skkTags: [
      { code: "F.45.2.0.4.0.0.19.II.01", name: "Merencanakan Sistem Mekanikal Bangunan" },
      { code: "F.45.2.0.4.0.0.19.II.03", name: "Melakukan Koordinasi Desain MEP" },
    ],
    description: "Panduan lengkap penggunaan Revit MEP untuk koordinasi sistem mekanikal, elektrikal, dan plumbing pada proyek gedung. Termasuk clash detection dan pembuatan shop drawing MEP.",
    highlights: [
      "Revit MEP 2024 — lisensi student gratis tersedia",
      "Template proyek gedung komersial siap latihan",
      "Clash detection & resolusi koordinasi",
      "Sertifikat Autodesk diakui internasional",
    ],
    curriculum: [
      { title: "Pengantar BIM & Workflow MEP", duration: "40 mnt", type: "video" },
      { title: "Setup Proyek & Linking Model", duration: "55 mnt", type: "video" },
      { title: "Modeling Sistem HVAC", duration: "90 mnt", type: "video" },
      { title: "Quiz: Konsep MEP Coordination", duration: "20 mnt", type: "quiz" },
      { title: "Modeling Sistem Plumbing", duration: "75 mnt", type: "video" },
      { title: "Clash Detection & Navisworks", duration: "60 mnt", type: "video" },
    ],
    url: "https://learn.autodesk.com",
    isBestSeller: false,
    isFeatured: true,
    isNew: false,
    sortOrder: 4,
  },
  {
    id: "manpro-wbs-schedule",
    title: "Membuat WBS & Jadwal Proyek dengan MS Project",
    provider: "YouTube — Pak Budi Konstruksi",
    providerLogo: "📺",
    thumbnail: "from-rose-500 to-pink-500",
    type: "video",
    price: "gratis",
    priceIdr: null,
    priceOriginalIdr: null,
    rating: 4.6,
    ratingCount: 4200,
    durationMinutes: 195,
    videoCount: 15,
    quizCount: 0,
    hasCertificate: false,
    jabker: ["manajer_proyek", "pengawas_lapangan"],
    skkTags: [
      { code: "M.711000.012.01", name: "Menyusun Jadwal Pelaksanaan Proyek" },
      { code: "M.711000.014.01", name: "Mengendalikan Waktu Pelaksanaan" },
    ],
    description: "Playlist YouTube lengkap membahas pembuatan Work Breakdown Structure (WBS), Gantt Chart, Baseline, dan pelaporan kemajuan proyek menggunakan Microsoft Project 2021.",
    highlights: [
      "15 video praktis — langsung praktek",
      "Template MS Project tersedia di deskripsi",
      "Metode Earned Value Analysis (EVA)",
      "Update Agustus 2024 — fitur terbaru MS Project",
    ],
    curriculum: [
      { title: "Pengantar MS Project & Interface", duration: "12 mnt", type: "video" },
      { title: "Membuat WBS & Hierarki Task", duration: "18 mnt", type: "video" },
      { title: "Menetapkan Durasi & Predecessor", duration: "15 mnt", type: "video" },
      { title: "Resource Planning & Leveling", duration: "20 mnt", type: "video" },
      { title: "Baseline & Tracking Progress", duration: "25 mnt", type: "video" },
      { title: "Laporan & S-Curve", duration: "15 mnt", type: "video" },
    ],
    url: "https://youtube.com",
    isBestSeller: true,
    isFeatured: false,
    isNew: false,
    sortOrder: 5,
  },
  {
    id: "ahli-struktur-desain-kolom",
    title: "Desain Kolom & Balok Beton Bertulang SNI 2847",
    provider: "HAKI Webinar",
    providerLogo: "🏛️",
    thumbnail: "from-amber-500 to-orange-500",
    type: "webinar",
    price: "gratis",
    priceIdr: null,
    priceOriginalIdr: null,
    rating: 4.9,
    ratingCount: 1876,
    durationMinutes: 360,
    videoCount: 18,
    quizCount: 6,
    hasCertificate: true,
    jabker: ["ahli_struktur"],
    skkTags: [
      { code: "F.45.2.0.1.0.0.19.III.01", name: "Merencanakan Struktur Beton Bertulang" },
      { code: "F.45.2.0.1.0.0.19.III.02", name: "Menghitung Gaya Dalam Struktur" },
    ],
    description: "Webinar HAKI (Himpunan Ahli Konstruksi Indonesia) membahas prosedur desain kolom, balok, dan pelat beton bertulang sesuai SNI 2847:2019 dan SNI 1726:2019 (beban gempa).",
    highlights: [
      "Metode desain LRFD sesuai SNI 2847:2019",
      "Contoh hitungan kolom dengan beban gempa",
      "Spreadsheet desain otomatis disediakan",
      "Narasumber: Prof. dari ITB & UI",
    ],
    curriculum: [
      { title: "Review Konsep Mekanika Struktur", duration: "45 mnt", type: "video" },
      { title: "Beban Gempa SNI 1726 & Faktor Reduksi", duration: "60 mnt", type: "video" },
      { title: "Desain Kolom — Interaksi Aksial-Momen", duration: "75 mnt", type: "video" },
      { title: "Quiz: Kolom & Kapasitas", duration: "20 mnt", type: "quiz" },
      { title: "Desain Balok & Tulangan Geser", duration: "80 mnt", type: "video" },
    ],
    url: "https://haki.or.id",
    isBestSeller: false,
    isFeatured: true,
    isNew: false,
    sortOrder: 6,
  },
  {
    id: "k3-kebakaran-apar",
    title: "Pencegahan & Penanganan Kebakaran Konstruksi",
    provider: "YouTube — K3 Academy ID",
    providerLogo: "📺",
    thumbnail: "from-red-500 to-orange-600",
    type: "video",
    price: "gratis",
    priceIdr: null,
    priceOriginalIdr: null,
    rating: 4.5,
    ratingCount: 3100,
    durationMinutes: 120,
    videoCount: 10,
    quizCount: 3,
    hasCertificate: false,
    jabker: ["ahli_k3_konstruksi", "pengawas_k3_konstruksi"],
    skkTags: [
      { code: "F.45.2.0.0.0.0.0.05", name: "Mengelola Penanganan Darurat K3" },
    ],
    description: "Seri video YouTube membahas proteksi kebakaran di proyek konstruksi — jenis APAR, prosedur evakuasi, identifikasi sumber api, dan pembuatan emergency response plan.",
    highlights: [
      "Demonstrasi langsung penggunaan APAR",
      "Template Emergency Response Plan",
      "Prosedur sesuai Permen 04/MEN/1980",
      "Cocok untuk refresher K3 sebelum inspeksi",
    ],
    curriculum: [
      { title: "Segitiga Api & Klasifikasi Kebakaran", duration: "12 mnt", type: "video" },
      { title: "Jenis & Cara Pakai APAR", duration: "15 mnt", type: "video" },
      { title: "Sistem Deteksi & Alarm Kebakaran", duration: "18 mnt", type: "video" },
      { title: "Quiz: Prosedur Kebakaran", duration: "10 mnt", type: "quiz" },
      { title: "Membuat Emergency Response Plan", duration: "25 mnt", type: "video" },
    ],
    url: "https://youtube.com",
    isBestSeller: false,
    isFeatured: false,
    isNew: true,
    sortOrder: 7,
  },
  {
    id: "pengawas-as-built-drawing",
    title: "Membuat As-Built Drawing dengan AutoCAD Civil 3D",
    provider: "Skill Academy Pro",
    providerLogo: "🎓",
    thumbnail: "from-cyan-500 to-sky-500",
    type: "video",
    price: "berbayar",
    priceIdr: 255000,
    priceOriginalIdr: 470000,
    rating: 4.9,
    ratingCount: 892,
    durationMinutes: 494,
    videoCount: 33,
    quizCount: 12,
    hasCertificate: true,
    jabker: ["pengawas_lapangan", "quantity_surveyor"],
    skkTags: [
      { code: "F.45.2.0.1.1.0.76.II.05", name: "Membuat Laporan Teknis Pengawasan" },
      { code: "M.711000.008.01", name: "Mendokumentasikan Kemajuan Pekerjaan" },
    ],
    description: "Kelas bundle 2 kursus dari Skill Academy Pro — AutoCAD 2D untuk pengawas lapangan dan pembuatan As-Built Drawing berstandar PUPR. Lengkap dengan 33 video dan 12 kuis.",
    highlights: [
      "Bundle 2 kursus — akses seumur hidup",
      "Template As-Built Drawing sesuai standar PUPR",
      "AutoCAD 2024 — fitur terbaru",
      "Sertifikat Skill Academy Pro",
    ],
    curriculum: [
      { title: "Interface AutoCAD & Setting Workspace", duration: "30 mnt", type: "video" },
      { title: "Menggambar Denah & Potongan", duration: "55 mnt", type: "video" },
      { title: "Layer, Dimensi & Notasi", duration: "45 mnt", type: "video" },
      { title: "Quiz: AutoCAD Dasar", duration: "15 mnt", type: "quiz" },
      { title: "Prosedur As-Built Drawing PUPR", duration: "40 mnt", type: "video" },
      { title: "Plotting & Transmittal Gambar", duration: "35 mnt", type: "video" },
    ],
    url: "https://skillacademy.com/bundle-course/teknik-mahir-menggunakan-microsoft-excel",
    isBestSeller: true,
    isFeatured: false,
    isNew: false,
    sortOrder: 8,
  },
  {
    id: "qs-esimpan-tutorial",
    title: "Panduan Lengkap Aplikasi ESIMPAN Kemnaker",
    provider: "Kemnaker Diklatkerja",
    providerLogo: "🏛️",
    thumbnail: "from-indigo-500 to-blue-600",
    type: "diklatkerja",
    price: "gratis",
    priceIdr: null,
    priceOriginalIdr: null,
    rating: 4.4,
    ratingCount: 5600,
    durationMinutes: 90,
    videoCount: 8,
    quizCount: 2,
    hasCertificate: false,
    jabker: ["quantity_surveyor", "pengawas_lapangan", "manajer_proyek"],
    skkTags: [
      { code: "M.711000.008.01", name: "Mendokumentasikan Kemajuan Pekerjaan" },
    ],
    description: "Tutorial resmi Kemnaker tentang cara mengoperasikan ESIMPAN (Elektronik Sistem Informasi Manajemen Pengembangan dan Pemberdayaan Tenaga Kerja) — upload bukti PKB, mengajukan SKK, dan tracking status.",
    highlights: [
      "Tutorial resmi dari Kemnaker",
      "Langkah upload bukti PKB di ESIMPAN",
      "Cara pengajuan SKK online",
      "Update 2024 — antarmuka ESIMPAN terbaru",
    ],
    curriculum: [
      { title: "Registrasi & Login ESIMPAN", duration: "10 mnt", type: "video" },
      { title: "Mengisi Profil TKK di ESIMPAN", duration: "15 mnt", type: "video" },
      { title: "Upload Bukti Kegiatan PKB", duration: "20 mnt", type: "video" },
      { title: "Pengajuan SKK & Status Tracking", duration: "25 mnt", type: "video" },
    ],
    url: "https://www.diklatkerja.kemnaker.go.id",
    isBestSeller: false,
    isFeatured: false,
    isNew: true,
    sortOrder: 9,
  },
];

// ─── AI Reviews ───────────────────────────────────────────────────────────────

const AI_REVIEWS: Array<{ courseId: string; platform: string; platformIcon: string; rating: number; relevanceScore: number; comment: string; reviewedAt: string }> = [
  // k3-dasar-pupr
  { courseId: "k3-dasar-pupr", platform: "ChatGPT", platformIcon: "🤖", rating: 4.8, relevanceScore: 95, comment: "Konten diklatkerja ini sangat komprehensif dan langsung relevan dengan standar SMK3 berbasis PP 50/2012 dan ISO 45001. Penyampaian materi inspeksi lapangan sangat praktis — dilengkapi formulir siap pakai yang jarang ada di kursus online lain. Cocok sebagai bukti PKB formal karena berasal dari sumber resmi Kemnaker.", reviewedAt: "Oktober 2025" },
  { courseId: "k3-dasar-pupr", platform: "Gemini", platformIcon: "🔮", rating: 4.7, relevanceScore: 92, comment: "Diklatkerja ini memenuhi kriteria PKB yang baik: bersumber resmi, sistematis, dan mencakup unit SKK yang diklaim. Studi kasus insiden nyata meningkatkan nilai bukti belajar — peserta bukan hanya tahu teori tapi bisa mendemonstrasikan aplikasi. Satu catatan: durasi per sesi bisa lebih pendek untuk memudahkan konsumsi mobile.", reviewedAt: "Oktober 2025" },
  { courseId: "k3-dasar-pupr", platform: "Claude", platformIcon: "🟠", rating: 4.9, relevanceScore: 96, comment: "Dari perspektif kualitas konten pendidikan profesional, ini adalah salah satu diklatkerja K3 terbaik yang tersedia secara gratis. Alur dari regulasi → identifikasi bahaya → inspeksi → penanganan insiden sangat logis. Kepatuhan terhadap hierarki regulasi (UU → PP → Permen) memberikan landasan hukum yang solid bagi peserta.", reviewedAt: "September 2025" },
  { courseId: "k3-dasar-pupr", platform: "Microsoft Copilot", platformIcon: "💙", rating: 4.6, relevanceScore: 90, comment: "Konten sejajar dengan standar pelatihan K3 internasional (NEBOSH/IOSH level entry). Untuk konteks sertifikasi BNSP, cakupan SMK3 dan inspeksi lapangan sangat baik. Rekaman berkualitas cukup untuk pembelajaran mandiri. Direkomendasikan sebagai fondasi sebelum mengikuti uji kompetensi SKK K3.", reviewedAt: "September 2025" },
  { courseId: "k3-dasar-pupr", platform: "Perplexity", platformIcon: "🔍", rating: 4.7, relevanceScore: 93, comment: "Verifikasi silang dengan regulasi terkini: materi selaras dengan Permen PUPR No. 21 Tahun 2019 tentang K3 Konstruksi. Materi penanganan insiden memenuhi persyaratan pelaporan Kemnaker. Sangat direkomendasikan sebagai bukti PKB — sumber resmi pemerintah memiliki bobot lebih tinggi di mata asesor.", reviewedAt: "Oktober 2025" },

  // qs-bop-perhitungan
  { courseId: "qs-bop-perhitungan", platform: "ChatGPT", platformIcon: "🤖", rating: 4.9, relevanceScore: 94, comment: "Kursus Skill Academy ini adalah salah satu yang terbaik untuk QS di Indonesia. Template Excel BOQ dan RAB yang disediakan sangat praktis — peserta langsung bisa menerapkan di proyek nyata. Penggunaan SNI harga satuan terkini memastikan relevansi untuk proyek pemerintah maupun swasta. Cocok untuk PKB karena ada sertifikat yang bisa dilampirkan.", reviewedAt: "Oktober 2025" },
  { courseId: "qs-bop-perhitungan", platform: "Gemini", platformIcon: "🔮", rating: 4.8, relevanceScore: 91, comment: "Konten sangat sistematis: mulai dari konsep dasar estimasi hingga manajemen change order. Untuk QS yang hendak mengambil SKK, kursus ini membantu memahami konteks teoritis yang sering ditanyakan dalam uji kompetensi. Studi kasus gedung 5 lantai realistis untuk skala proyek yang biasa dihadapi TKK Indonesia.", reviewedAt: "Oktober 2025" },
  { courseId: "qs-bop-perhitungan", platform: "Claude", platformIcon: "🟠", rating: 4.9, relevanceScore: 95, comment: "Dari sisi kualitas pedagogis, urutan materi sangat baik — gradasi dari membaca gambar → menghitung volume → analisa HSP → RAB mencerminkan kompetensi QS secara holistik. Penjelasan analisa harga satuan SNI sangat jarang tersedia di kursus online lain. Nilai tambah signifikan untuk portofolio PKB.", reviewedAt: "September 2025" },
  { courseId: "qs-bop-perhitungan", platform: "Microsoft Copilot", platformIcon: "💙", rating: 4.7, relevanceScore: 89, comment: "Dibandingkan dengan kursus estimasi biaya di platform internasional (Coursera, Udemy), kursus ini unggul dalam konteks lokal: SNI, Permen PUPR, dan format RAB standar Indonesia. Sangat relevan untuk QS yang bekerja di proyek APBN/APBD. Template Excel kompatibel dengan proses pekerjaan sehari-hari.", reviewedAt: "September 2025" },
  { courseId: "qs-bop-perhitungan", platform: "Perplexity", platformIcon: "🔍", rating: 4.8, relevanceScore: 93, comment: "Verifikasi: SNI yang digunakan dalam kursus ini (SNI 7835 series) adalah versi terkini yang berlaku. Materi Hlookup/Vlookup untuk BOQ sangat relevan — sesuai dengan kebutuhan praktik QS modern. Sertifikat Skill Academy Pro diakui beberapa lembaga sertifikasi sebagai bukti pembelajaran formal.", reviewedAt: "Oktober 2025" },

  // pengawas-lapangan-mutu
  { courseId: "pengawas-lapangan-mutu", platform: "ChatGPT", platformIcon: "🤖", rating: 4.7, relevanceScore: 93, comment: "Webinar LPJK ini mencakup prosedur pengendalian mutu beton yang sangat praktis. Prosedur slump test dan uji kuat tekan yang dijelaskan sesuai dengan SNI 2847:2019 — ini penting karena beberapa kursus online masih menggunakan SNI lama. Formulir pengendalian mutu yang disediakan langsung bisa digunakan di lapangan.", reviewedAt: "Oktober 2025" },
  { courseId: "pengawas-lapangan-mutu", platform: "Gemini", platformIcon: "🔮", rating: 4.6, relevanceScore: 90, comment: "Konten tepat sasaran untuk pengawas lapangan dan ahli struktur yang menghadapi pekerjaan beton. Penjelasan acceptance criteria sangat jelas — hal yang sering menjadi titik perdebatan antara kontraktor dan pengawas di lapangan. Webinar format memungkinkan peserta menyaksikan demonstrasi langsung.", reviewedAt: "Oktober 2025" },
  { courseId: "pengawas-lapangan-mutu", platform: "Claude", platformIcon: "🟠", rating: 4.8, relevanceScore: 94, comment: "Kualitas akademis webinar ini setara dengan training in-house dari kontraktor besar. Pembahasan cacat pengerjaan dan tindakan korektif sangat berguna — ini adalah kompetensi yang jarang dipelajari secara sistematis. Untuk PKB, ini adalah bukti belajar yang kuat karena sumbernya LPJK (lembaga resmi).", reviewedAt: "September 2025" },
  { courseId: "pengawas-lapangan-mutu", platform: "Microsoft Copilot", platformIcon: "💙", rating: 4.5, relevanceScore: 88, comment: "Dibandingkan dengan standar ACI (American Concrete Institute) untuk quality control beton, materi ini sudah cukup komprehensif untuk level pengawas lapangan. Satu hal yang bisa ditingkatkan adalah penjelasan tentang core drilling sebagai verifikasi kuat tekan beton in-situ.", reviewedAt: "September 2025" },
  { courseId: "pengawas-lapangan-mutu", platform: "Perplexity", platformIcon: "🔍", rating: 4.7, relevanceScore: 91, comment: "Webinar LPJK memiliki legitimasi khusus sebagai bukti PKB — LPJK adalah lembaga pengembangan jasa konstruksi yang diakui Kemenpu. Materi selaras dengan persyaratan teknis Permen PUPR tentang standar mutu konstruksi. Sangat direkomendasikan sebagai bukti belajar untuk pengawas yang sedang mempersiapkan sertifikasi.", reviewedAt: "Oktober 2025" },

  // mep-koordinasi-bim
  { courseId: "mep-koordinasi-bim", platform: "ChatGPT", platformIcon: "🤖", rating: 4.8, relevanceScore: 88, comment: "Kursus Autodesk ini berkualitas tinggi dan relevan untuk ahli MEP yang bekerja di proyek gedung. Penguasaan Revit MEP adalah kompetensi yang semakin diminta di proyek-proyek besar. Untuk PKB, kursus ini mendemonstrasikan kemampuan adopsi teknologi — yang merupakan salah satu kriteria PKB yang diakui LPJK.", reviewedAt: "Oktober 2025" },
  { courseId: "mep-koordinasi-bim", platform: "Gemini", platformIcon: "🔮", rating: 4.7, relevanceScore: 86, comment: "Clash detection dengan Navisworks adalah kompetensi yang membedakan MEP engineer biasa dengan yang kompetitif. Kursus ini menjelaskan workflow koordinasi secara lengkap. Relevan untuk TKK MEP yang ingin menunjukkan kompetensi di area BIM — area yang sedang berkembang dalam regulasi konstruksi Indonesia.", reviewedAt: "Oktober 2025" },
  { courseId: "mep-koordinasi-bim", platform: "Claude", platformIcon: "🟠", rating: 4.9, relevanceScore: 90, comment: "Dari perspektif pengembangan profesional, kursus ini memberikan nilai tinggi — Revit MEP adalah standar industri global. Sertifikat Autodesk diakui secara internasional, yang memperkuat portofolio PKB. Konten tentang koordinasi multi-disiplin sangat relevan untuk proyek gedung Indonesia yang semakin kompleks.", reviewedAt: "September 2025" },
  { courseId: "mep-koordinasi-bim", platform: "Microsoft Copilot", platformIcon: "💙", rating: 4.8, relevanceScore: 91, comment: "Sebagai platform Microsoft, kami melihat Revit MEP dan Navisworks sebagai standar industri yang kami dukung. Kursus ini memenuhi kebutuhan kompetensi BIM level intermediate. Sangat relevan untuk proyek infrastruktur yang mewajibkan BIM — sesuai SE Menteri PUPR No. 22/2020.", reviewedAt: "September 2025" },
  { courseId: "mep-koordinasi-bim", platform: "Perplexity", platformIcon: "🔍", rating: 4.6, relevanceScore: 87, comment: "SE Menteri PUPR No. 22/2020 mewajibkan BIM untuk proyek gedung di atas Rp100M — membuat kompetensi Revit MEP semakin strategis. Kursus ini langsung merespons kebutuhan regulasi tersebut. Untuk TKK MEP yang berambisi naik jenjang, ini adalah investasi belajar yang sangat worth it.", reviewedAt: "Oktober 2025" },

  // manpro-wbs-schedule
  { courseId: "manpro-wbs-schedule", platform: "ChatGPT", platformIcon: "🤖", rating: 4.6, relevanceScore: 89, comment: "Playlist YouTube ini sangat praktis untuk manajemen proyek konstruksi. Penjelasan WBS, baseline, dan EVA dalam konteks MS Project sangat relevan. Walau tidak ada sertifikat, nilai belajarnya tinggi — peserta bisa langsung mempraktikkan dalam pekerjaan. Untuk PKB, buat catatan refleksi sebagai pelengkap bukti.", reviewedAt: "Oktober 2025" },
  { courseId: "manpro-wbs-schedule", platform: "Gemini", platformIcon: "🔮", rating: 4.5, relevanceScore: 87, comment: "Konten teknis MS Project yang diajarkan sesuai dengan kebutuhan proyek skala menengah. EVA (Earned Value Analysis) adalah kompetensi yang jarang diajarkan secara praktis — kursus ini melakukannya dengan baik. Untuk PKB, screenshot laporan yang dibuat dari latihan bisa menjadi bukti hasil belajar.", reviewedAt: "Oktober 2025" },
  { courseId: "manpro-wbs-schedule", platform: "Claude", platformIcon: "🟠", rating: 4.7, relevanceScore: 90, comment: "Video YouTube yang berkualitas tinggi — penjelasan konseptual dan demonstrasi praktis seimbang. Metode EVA yang diajarkan sejalan dengan PMBOK Guide. Untuk portofolio PKB, peserta disarankan mendokumentasikan screenshot proyek MS Project yang mereka buat sendiri sebagai output nyata.", reviewedAt: "September 2025" },
  { courseId: "manpro-wbs-schedule", platform: "Microsoft Copilot", platformIcon: "💙", rating: 4.8, relevanceScore: 92, comment: "Microsoft Project adalah tools resmi Microsoft yang kami kembangkan untuk manajemen proyek profesional. Kursus ini mengajarkan fitur-fitur kunci dengan sangat baik. Untuk TKK yang menggunakannya di proyek nyata, ini adalah kompetensi yang langsung bisa didemonstrasikan saat uji kompetensi.", reviewedAt: "September 2025" },
  { courseId: "manpro-wbs-schedule", platform: "Perplexity", platformIcon: "🔍", rating: 4.5, relevanceScore: 86, comment: "MS Project adalah standar industri untuk perencanaan jadwal proyek di Indonesia. Template yang disediakan kompatibel dengan format laporan kemajuan yang diminta oleh owner proyek pemerintah. Sangat relevan untuk manajer proyek dan pengawas yang harus membuat laporan mingguan/bulanan.", reviewedAt: "Oktober 2025" },

  // ahli-struktur-desain-kolom
  { courseId: "ahli-struktur-desain-kolom", platform: "ChatGPT", platformIcon: "🤖", rating: 4.9, relevanceScore: 96, comment: "Webinar HAKI dengan narasumber dari ITB dan UI ini adalah salah satu konten teknik struktur terbaik yang tersedia secara gratis di Indonesia. Penjelasan desain kolom dengan beban gempa SNI 1726 sangat komprehensif — topik yang sangat relevan mengingat Indonesia berada di zona gempa tinggi.", reviewedAt: "Oktober 2025" },
  { courseId: "ahli-struktur-desain-kolom", platform: "Gemini", platformIcon: "🔮", rating: 4.9, relevanceScore: 95, comment: "Kualitas akademis sangat tinggi — narasumber dari perguruan tinggi top Indonesia memberikan jaminan kebenaran teknis. Spreadsheet desain otomatis yang disediakan adalah nilai tambah luar biasa yang jarang ada di webinar lain. Untuk ahli struktur yang hendak naik jenjang, ini adalah bukti PKB yang sangat kuat.", reviewedAt: "Oktober 2025" },
  { courseId: "ahli-struktur-desain-kolom", platform: "Claude", platformIcon: "🟠", rating: 4.9, relevanceScore: 97, comment: "Konten ini setara dengan materi kuliah S2 Teknik Sipil yang dikemas untuk praktisi. Pembahasan desain interaksi aksial-momen pada kolom adalah topik advanced yang membutuhkan narasumber berkompeten — HAKI memenuhi standar ini. Sangat direkomendasikan sebagai bukti PKB untuk ahli struktur jenjang 8–9.", reviewedAt: "September 2025" },
  { courseId: "ahli-struktur-desain-kolom", platform: "Microsoft Copilot", platformIcon: "💙", rating: 4.8, relevanceScore: 93, comment: "Dari perspektif standar teknis, materi selaras dengan SNI 2847:2019 dan SNI 1726:2019 yang saat ini berlaku. Spreadsheet desain kolom yang disediakan mengikuti format yang dapat diverifikasi — penting untuk memenuhi standar dokumen teknis proyek. Konten sangat reliable untuk digunakan sebagai referensi desain.", reviewedAt: "September 2025" },
  { courseId: "ahli-struktur-desain-kolom", platform: "Perplexity", platformIcon: "🔍", rating: 4.9, relevanceScore: 96, comment: "HAKI (Himpunan Ahli Konstruksi Indonesia) adalah organisasi profesi yang diakui LPJK — webinar mereka memiliki legitimasi khusus sebagai bukti PKB profesional. Verifikasi: SNI yang digunakan adalah versi 2019 yang berlaku. Sangat direkomendasikan, terutama karena gratis dan bersumber dari asosiasi profesi resmi.", reviewedAt: "Oktober 2025" },

  // k3-kebakaran-apar
  { courseId: "k3-kebakaran-apar", platform: "ChatGPT", platformIcon: "🤖", rating: 4.5, relevanceScore: 87, comment: "Video YouTube ini informatif dan praktis untuk topik K3 kebakaran. Demonstrasi langsung penggunaan APAR adalah nilai tambah yang penting — ini adalah kompetensi hands-on yang harus dilihat secara visual. Template ERP yang disediakan berguna sebagai bukti hasil belajar yang bisa dilampirkan.", reviewedAt: "Oktober 2025" },
  { courseId: "k3-kebakaran-apar", platform: "Gemini", platformIcon: "🔮", rating: 4.4, relevanceScore: 85, comment: "Konten sesuai dengan Permen 04/MEN/1980 tentang syarat APAR. Untuk pengawas K3 yang mempersiapkan sertifikasi, materi ini mencakup kompetensi yang sering diuji — identifikasi jenis api, pemilihan APAR yang tepat, dan prosedur evakuasi. Cocok sebagai bukti belajar refresher.", reviewedAt: "Oktober 2025" },
  { courseId: "k3-kebakaran-apar", platform: "Claude", platformIcon: "🟠", rating: 4.6, relevanceScore: 88, comment: "Sebagai konten YouTube gratis, kualitas produksi dan kedalaman materi sangat baik. Penjelasan 4 kelas kebakaran (A/B/C/D) dan pemilihan APAR yang tepat sangat jelas. Untuk PKB, peserta disarankan mendokumentasikan: sudah menonton + telah membuat ERP dari template yang disediakan.", reviewedAt: "September 2025" },
  { courseId: "k3-kebakaran-apar", platform: "Microsoft Copilot", platformIcon: "💙", rating: 4.3, relevanceScore: 83, comment: "Materi cukup untuk level awareness K3 kebakaran. Untuk level kompetensi yang lebih dalam, bisa dikombinasikan dengan diklatkerja K3 formal. Sebagai bukti PKB, video ini perlu dilengkapi dengan bukti penerapan nyata seperti foto pengecekan APAR di proyek.", reviewedAt: "September 2025" },
  { courseId: "k3-kebakaran-apar", platform: "Perplexity", platformIcon: "🔍", rating: 4.5, relevanceScore: 86, comment: "Regulasi yang direferensikan (Permen 04/MEN/1980) masih berlaku dan relevan. Untuk konteks konstruksi, K3 kebakaran adalah kompetensi wajib yang diuji dalam SKK K3. Video ini baik sebagai pengenalan, namun perlu dikombinasikan dengan praktik lapangan untuk memenuhi standar kompetensi penuh.", reviewedAt: "Oktober 2025" },

  // pengawas-as-built-drawing
  { courseId: "pengawas-as-built-drawing", platform: "ChatGPT", platformIcon: "🤖", rating: 4.9, relevanceScore: 93, comment: "Bundle 2 kursus Skill Academy ini sangat komprehensif untuk pengawas lapangan dan QS. Kombinasi AutoCAD 2D + As-Built Drawing PUPR dalam satu paket sangat efisien. Standar PUPR yang diajarkan langsung applicable untuk proyek pemerintah. Sertifikat Skill Academy Pro adalah bukti PKB yang kuat.", reviewedAt: "Oktober 2025" },
  { courseId: "pengawas-as-built-drawing", platform: "Gemini", platformIcon: "🔮", rating: 4.8, relevanceScore: 91, comment: "As-Built Drawing adalah output wajib pengawas lapangan — kursus ini mengajarkan cara membuatnya sesuai standar yang diminta owner/konsultan. Penjelasan plotting dan transmittal gambar sangat praktis. Untuk PKB, peserta bisa melampirkan contoh As-Built Drawing yang dibuat selama kursus.", reviewedAt: "Oktober 2025" },
  { courseId: "pengawas-as-built-drawing", platform: "Claude", platformIcon: "🟠", rating: 4.9, relevanceScore: 94, comment: "Kualitas bundle ini sangat baik — alur dari AutoCAD dasar hingga As-Built Drawing PUPR sangat logis. Kemampuan membuat As-Built Drawing yang akurat adalah kompetensi inti pengawas yang sering diuji dalam sertifikasi. Template gambar yang disediakan langsung bisa digunakan sebagai portofolio.", reviewedAt: "September 2025" },
  { courseId: "pengawas-as-built-drawing", platform: "Microsoft Copilot", platformIcon: "💙", rating: 4.7, relevanceScore: 90, comment: "AutoCAD adalah standar industri yang kami akui kualitasnya. Kursus ini mengajarkan workflow yang efisien — dari modeling hingga plotting. Untuk pengawas lapangan, kemampuan AutoCAD yang baik meningkatkan efisiensi dokumentasi lapangan secara signifikan.", reviewedAt: "September 2025" },
  { courseId: "pengawas-as-built-drawing", platform: "Perplexity", platformIcon: "🔍", rating: 4.8, relevanceScore: 92, comment: "Standar As-Built Drawing PUPR yang diajarkan sesuai dengan Peraturan Menteri PUPR tentang pedoman teknis pembangunan. Untuk proyek APBN, As-Built Drawing adalah dokumen wajib serah terima — membuat kompetensi ini sangat relevan. Bundle harga Rp255.000 sangat worth it untuk nilai kompetensi yang didapatkan.", reviewedAt: "Oktober 2025" },

  // qs-esimpan-tutorial
  { courseId: "qs-esimpan-tutorial", platform: "ChatGPT", platformIcon: "🤖", rating: 4.4, relevanceScore: 85, comment: "Tutorial ESIMPAN resmi dari Kemnaker ini wajib ditonton oleh semua TKK. Kemampuan mengoperasikan ESIMPAN adalah kompetensi praktis yang langsung diperlukan untuk proses sertifikasi. Panduan upload bukti PKB sangat berguna — banyak TKK yang mengalami kesulitan di tahap ini.", reviewedAt: "Oktober 2025" },
  { courseId: "qs-esimpan-tutorial", platform: "Gemini", platformIcon: "🔮", rating: 4.3, relevanceScore: 83, comment: "Tutorial ini menjawab kebutuhan yang sangat spesifik dan praktis — cara menggunakan sistem resmi pemerintah. Untuk PKB, memahami ESIMPAN bukan hanya tentang teknis, tapi juga memastikan bukti belajar yang dikumpulkan valid secara administratif. Direkomendasikan sebagai bagian dari onboarding PKB.", reviewedAt: "Oktober 2025" },
  { courseId: "qs-esimpan-tutorial", platform: "Claude", platformIcon: "🟠", rating: 4.5, relevanceScore: 87, comment: "Konten sangat relevan dan tepat sasaran — ini adalah pengetahuan yang tidak bisa diasumsikan sudah dimiliki TKK. Banyak TKK yang kompeten secara teknis tapi gagal di proses administrasi ESIMPAN. Tutorial ini membantu menutup gap tersebut. Gratis dan dari sumber resmi — tidak ada alasan untuk tidak menontonnya.", reviewedAt: "September 2025" },
  { courseId: "qs-esimpan-tutorial", platform: "Microsoft Copilot", platformIcon: "💙", rating: 4.2, relevanceScore: 82, comment: "Tutorial sistem pemerintah yang cukup jelas dan to-the-point. Antarmuka ESIMPAN yang digunakan adalah versi terbaru 2024. Untuk TKK yang baru pertama kali menggunakan sistem ini, tutorial sangat membantu menghindari kesalahan prosedural yang bisa menunda proses sertifikasi.", reviewedAt: "September 2025" },
  { courseId: "qs-esimpan-tutorial", platform: "Perplexity", platformIcon: "🔍", rating: 4.4, relevanceScore: 84, comment: "ESIMPAN adalah sistem resmi Kemnaker untuk pencatatan dan pengembangan TKK — pemahaman sistem ini sangat penting untuk memastikan bukti PKB tercatat dengan benar. Tutorial gratis dari sumber resmi ini adalah referensi yang harus ada di daftar belajar setiap TKK yang sedang mempersiapkan sertifikasi.", reviewedAt: "Oktober 2025" },
];

// ─── ASKOM Reviews ────────────────────────────────────────────────────────────

const ASKOM_REVIEWS: Array<{
  courseId: string; reviewerName: string; credential: string; institution: string;
  credentialNumber?: string; rating: number; relevanceScore: number;
  recommendation: string; comment: string; strengths: string[]; notes?: string; reviewedAt: string;
}> = [
  {
    courseId: "k3-dasar-pupr",
    reviewerName: "Ir. Hendra Kusuma, M.T.",
    credential: "Asesor Kompetensi Bidang K3 Konstruksi",
    institution: "LSP Konstruksi Indonesia — BNSP",
    credentialNumber: "MET.000.002341",
    rating: 4.9, relevanceScore: 97,
    recommendation: "direkomendasikan",
    comment: "Saya telah meninjau modul diklatkerja ini secara menyeluruh terhadap standar kompetensi SKK K3 Konstruksi Jenjang 6–8. Konten mencakup seluruh elemen kompetensi pada unit F.45.2.0.0.0.0.0.01 dan F.45.2.0.0.0.0.0.02 dengan kedalaman yang memadai. Penggunaan studi kasus insiden nyata (jatuh dari ketinggian) memberikan konteks yang sangat baik untuk assessment portofolio.",
    strengths: [
      "Sumber resmi Kemnaker — memiliki legitimasi hukum sebagai bukti PKB",
      "Alur materi sesuai hierarki kompetensi SKK",
      "Formulir inspeksi siap pakai dapat langsung dijadikan lampiran portofolio",
      "Studi kasus insiden mendukung demonstrasi kompetensi pada level aplikasi",
    ],
    reviewedAt: "November 2025",
  },
  {
    courseId: "qs-bop-perhitungan",
    reviewerName: "Drs. Agus Setiawan, M.M.",
    credential: "Asesor Kompetensi Bidang Quantity Surveying",
    institution: "LSP Jasa Konstruksi — BNSP",
    credentialNumber: "MET.000.003892",
    rating: 4.8, relevanceScore: 92,
    recommendation: "direkomendasikan",
    comment: "Kursus ini memiliki kedalaman yang cukup untuk mendukung klaim kompetensi pada unit M.711000.003.01 (menghitung volume) dan M.711000.005.01 (menyusun RAB). Penyajian materi analisa harga satuan SNI sangat komprehensif. Template yang disediakan dapat digunakan langsung sebagai lampiran portofolio APL 02.",
    strengths: [
      "Cakupan unit SKK lengkap — volume, HSP, dan RAB dalam satu kursus",
      "Template Excel dapat dijadikan bukti produk kerja (portofolio)",
      "Studi kasus nyata mendukung demonstrasi kompetensi",
      "Sertifikat Skill Academy Pro dapat dilampirkan di berkas APL",
    ],
    reviewedAt: "November 2025",
  },
  {
    courseId: "pengawas-lapangan-mutu",
    reviewerName: "Ir. Dewi Rahayu, M.T.",
    credential: "Asesor Kompetensi Bidang Pengawasan Konstruksi",
    institution: "LSP Konstruksi Indonesia — BNSP",
    credentialNumber: "MET.000.005127",
    rating: 4.7, relevanceScore: 93,
    recommendation: "direkomendasikan_dengan_catatan",
    comment: "Webinar ini relevan untuk mendukung klaim kompetensi pada unit F.45.2.0.1.1.0.76.II.01. Namun untuk pemenuhan unit secara lengkap, peserta perlu melengkapi dengan bukti pengalaman lapangan nyata — webinar saja tidak cukup untuk unit yang membutuhkan demonstrasi kompetensi langsung.",
    strengths: [
      "Sumber LPJK memberikan bobot legitimasi tinggi",
      "Prosedur SNI 2847:2019 yang dibahas up-to-date",
      "Formulir siap pakai memperkuat bukti portofolio",
    ],
    notes: "Untuk klaim unit F.45.2.0.1.1.0.76.II.01, bukti webinar ini harus dilengkapi dengan: (1) laporan inspeksi mutu beton dari proyek nyata, dan (2) foto/dokumentasi pengujian slump test yang pernah dilakukan oleh peserta.",
    reviewedAt: "November 2025",
  },
  {
    courseId: "mep-koordinasi-bim",
    reviewerName: "Ir. Rizky Pratama, M.Eng.",
    credential: "Asesor Kompetensi Bidang Mekanikal Elektrikal",
    institution: "LSP Ketenagalistrikan Indonesia — BNSP",
    credentialNumber: "MET.000.007634",
    rating: 4.8, relevanceScore: 89,
    recommendation: "direkomendasikan",
    comment: "Kursus ini relevan untuk mendukung kompetensi pada unit F.45.2.0.4.0.0.19.II.03 (koordinasi desain MEP). Penguasaan BIM tools seperti Revit MEP dan Navisworks adalah bukti kompetensi yang sangat dihargai dalam konteks sertifikasi modern. Sertifikat Autodesk yang diperoleh dapat dilampirkan langsung sebagai bukti PKB.",
    strengths: [
      "Sertifikat Autodesk internasional memperkuat portofolio",
      "Cakupan clash detection langsung applicable",
      "Konten mengikuti perkembangan regulasi BIM PUPR",
      "Template proyek siap latihan mempercepat learning curve",
    ],
    reviewedAt: "November 2025",
  },
  {
    courseId: "manpro-wbs-schedule",
    reviewerName: "Dr. Bambang Sutrisno, M.T.",
    credential: "Asesor Kompetensi Bidang Manajemen Proyek Konstruksi",
    institution: "LSP Konstruksi Indonesia — BNSP",
    credentialNumber: "MET.000.001823",
    rating: 4.6, relevanceScore: 88,
    recommendation: "direkomendasikan_dengan_catatan",
    comment: "Konten YouTube ini memiliki nilai pembelajaran yang baik untuk mendukung unit M.711000.012.01 dan M.711000.014.01. Namun karena tidak ada sertifikat, peserta perlu melengkapi bukti belajar dengan output kerja nyata dari proyek yang sedang ditangani.",
    strengths: [
      "Penjelasan EVA praktis dan langsung applicable",
      "Template MS Project berkualitas tinggi",
      "15 video sistematis mencakup workflow manajemen jadwal",
    ],
    notes: "Untuk klaim SKK Manajemen Jadwal, sertakan juga: (1) screenshot jadwal proyek nyata yang dibuat dengan MS Project, dan (2) laporan kemajuan yang pernah dibuat. Video YouTube saja tidak cukup tanpa bukti aplikasi nyata.",
    reviewedAt: "November 2025",
  },
  {
    courseId: "ahli-struktur-desain-kolom",
    reviewerName: "Prof. Dr. Ir. Suhendra, M.T.",
    credential: "Asesor Kompetensi Senior Bidang Rekayasa Struktur",
    institution: "LSP Konstruksi Indonesia — BNSP",
    credentialNumber: "MET.000.000312",
    rating: 5.0, relevanceScore: 98,
    recommendation: "direkomendasikan",
    comment: "Sebagai asesor yang juga aktif di HAKI, saya dapat mengkonfirmasi bahwa webinar ini diproduksi dengan standar akademis dan teknis yang sangat tinggi. Seluruh elemen kompetensi pada unit F.45.2.0.1.0.0.19.III.01 dan III.02 tercakup dengan baik. Spreadsheet desain yang disertakan dapat langsung dijadikan lampiran portofolio sebagai contoh produk kerja.",
    strengths: [
      "Narasumber dari ITB dan UI — jaminan kebenaran teknis tertinggi",
      "Spreadsheet desain siap pakai sebagai portofolio",
      "Cakupan SNI terkini (2019) — penting untuk proyek modern",
      "Webinar HAKI diakui sebagai CPD oleh PII dan INKINDO",
      "Gratis — tidak ada hambatan akses untuk TKK",
    ],
    reviewedAt: "November 2025",
  },
  {
    courseId: "k3-kebakaran-apar",
    reviewerName: "Ir. Rina Wulandari, M.K.K.K.",
    credential: "Asesor Kompetensi Bidang K3 Konstruksi",
    institution: "LSP Konstruksi Indonesia — BNSP",
    credentialNumber: "MET.000.008901",
    rating: 4.4, relevanceScore: 85,
    recommendation: "direkomendasikan_dengan_catatan",
    comment: "Video ini relevan sebagai bagian dari bukti belajar K3 kebakaran. Namun untuk pemenuhan unit F.45.2.0.0.0.0.0.05 (penanganan darurat K3), video saja tidak cukup — dibutuhkan bukti bahwa peserta telah terlibat dalam latihan evakuasi atau drills di proyek nyata.",
    strengths: [
      "Demonstrasi visual APAR mudah dipahami",
      "Template ERP dapat dijadikan lampiran portofolio",
      "Konten sesuai regulasi Permen 04/MEN/1980",
    ],
    notes: "Wajib melengkapi dengan: (1) foto latihan evakuasi atau APAR drill di proyek, (2) dokumen Emergency Response Plan yang telah ditandatangani kepala proyek, (3) absensi briefing K3 darurat yang pernah dilakukan.",
    reviewedAt: "November 2025",
  },
  {
    courseId: "pengawas-as-built-drawing",
    reviewerName: "Ir. Budi Hartono, M.T.",
    credential: "Asesor Kompetensi Bidang Pengawasan Konstruksi",
    institution: "LSP Konstruksi Indonesia — BNSP",
    credentialNumber: "MET.000.004521",
    rating: 4.8, relevanceScore: 92,
    recommendation: "direkomendasikan",
    comment: "Bundle kursus ini sangat relevan untuk mendukung klaim kompetensi pada unit F.45.2.0.1.1.0.76.II.05 dan M.711000.008.01. Template As-Built Drawing yang dipelajari dapat langsung dijadikan sampel portofolio. Sertifikat Skill Academy Pro yang diterbitkan dapat dilampirkan sebagai bukti formal di berkas APL 02.",
    strengths: [
      "Bundle 2 kursus — nilai kompetensi berlipat ganda",
      "Standar PUPR As-Built Drawing langsung applicable",
      "Sertifikat Skill Academy Pro dapat dilampirkan di APL",
      "Template gambar menjadi bukti produk kerja nyata",
      "Akses seumur hidup — bisa dijadikan referensi saat bekerja",
    ],
    reviewedAt: "November 2025",
  },
  {
    courseId: "qs-esimpan-tutorial",
    reviewerName: "Drs. Wahyu Nugroho, M.M.",
    credential: "Asesor Kompetensi & Konsultan Sertifikasi TKK",
    institution: "LSP Jasa Konstruksi — BNSP",
    credentialNumber: "MET.000.009123",
    rating: 4.5, relevanceScore: 86,
    recommendation: "direkomendasikan",
    comment: "Tutorial ESIMPAN ini sangat penting sebagai kompetensi administratif yang sering diabaikan. Banyak TKK yang gagal dalam proses sertifikasi bukan karena tidak kompeten, tapi karena salah menginput bukti di ESIMPAN. Memahami sistem ini adalah prasyarat untuk memaksimalkan seluruh bukti PKB yang telah dikumpulkan.",
    strengths: [
      "Tutorial resmi Kemnaker — informasi terpercaya dan akurat",
      "Panduan upload bukti PKB yang sering menjadi kendala",
      "Update 2024 — sesuai antarmuka ESIMPAN terkini",
      "Gratis — tidak ada hambatan akses",
    ],
    reviewedAt: "November 2025",
  },
];

// ─── Main ─────────────────────────────────────────────────────────────────────

async function main() {
  console.log("Seeding marketplace catalog...");

  // Upsert courses
  for (const c of COURSES) {
    await db
      .insert(marketplaceCourses)
      .values({
        id: c.id,
        title: c.title,
        provider: c.provider,
        providerLogo: c.providerLogo ?? null,
        thumbnail: c.thumbnail,
        type: c.type,
        price: c.price,
        priceIdr: c.priceIdr ?? null,
        priceOriginalIdr: c.priceOriginalIdr ?? null,
        rating: c.rating,
        ratingCount: c.ratingCount,
        durationMinutes: c.durationMinutes,
        videoCount: c.videoCount,
        quizCount: c.quizCount,
        hasCertificate: c.hasCertificate,
        jabker: c.jabker,
        skkTags: c.skkTags,
        description: c.description,
        highlights: c.highlights,
        curriculum: c.curriculum,
        url: c.url,
        isBestSeller: c.isBestSeller,
        isFeatured: c.isFeatured,
        isNew: c.isNew,
        sortOrder: c.sortOrder,
      })
      .onConflictDoUpdate({
        target: marketplaceCourses.id,
        set: {
          title: c.title,
          provider: c.provider,
          providerLogo: c.providerLogo ?? null,
          thumbnail: c.thumbnail,
          type: c.type,
          price: c.price,
          priceIdr: c.priceIdr ?? null,
          priceOriginalIdr: c.priceOriginalIdr ?? null,
          rating: c.rating,
          ratingCount: c.ratingCount,
          durationMinutes: c.durationMinutes,
          videoCount: c.videoCount,
          quizCount: c.quizCount,
          hasCertificate: c.hasCertificate,
          jabker: c.jabker,
          skkTags: c.skkTags,
          description: c.description,
          highlights: c.highlights,
          curriculum: c.curriculum,
          url: c.url,
          isBestSeller: c.isBestSeller,
          isFeatured: c.isFeatured,
          isNew: c.isNew,
          sortOrder: c.sortOrder,
        },
      });
    console.log(`  ✓ course: ${c.id}`);
  }

  // Clear + re-insert AI reviews (simpler than upsert by courseId+platform)
  await db.delete(marketplaceAiReviews);
  for (const r of AI_REVIEWS) {
    await db.insert(marketplaceAiReviews).values(r);
  }
  console.log(`  ✓ ${AI_REVIEWS.length} AI reviews inserted`);

  // Clear + re-insert ASKOM reviews
  await db.delete(marketplaceAskomReviews);
  for (const r of ASKOM_REVIEWS) {
    await db.insert(marketplaceAskomReviews).values({
      courseId: r.courseId,
      reviewerName: r.reviewerName,
      credential: r.credential,
      institution: r.institution,
      credentialNumber: r.credentialNumber ?? null,
      rating: r.rating,
      relevanceScore: r.relevanceScore,
      recommendation: r.recommendation,
      comment: r.comment,
      strengths: r.strengths,
      notes: r.notes ?? null,
      reviewedAt: r.reviewedAt,
    });
  }
  console.log(`  ✓ ${ASKOM_REVIEWS.length} ASKOM reviews inserted`);

  console.log("Done!");
  process.exit(0);
}

main().catch((e) => { console.error(e); process.exit(1); });
